const hardcodedUser = {
  _id: "1234567890abcdef",
  username: "mytestuser",
  firstName: "Jane",
  lastName: "Doe",
  email: "testuser@example.com",
  signupDate: "2023-01-01T00:00:00Z",
  pictureUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80",
  userSubmittedRecipes: [
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Chicken Alfredo",
      prepTime: 10,
      cookTime: 20,
      totalTime: 30,
      servings: 4,
      ingredients: ["chicken", "pasta", "cream", "parmesan", "garlic"],
      instructions: [
        "Cook pasta",
        "Sauté chicken",
        "Add cream and cheese",
        "Combine",
      ],
      imageUrl: "",
      cuisineRegion: "Italian",
      proteinChoice: "Chicken",
      dietaryRestriction: "",
      religiousRestriction: "",
      totalLikes: 15,
      totalReviews: 3,
      averageRating: 4.7,
      createdAt: "2024-04-01",
      userLiked: true,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Vegetable Stir Fry",
      prepTime: 10,
      cookTime: 10,
      totalTime: 20,
      servings: 2,
      ingredients: ["broccoli", "carrots", "bell pepper", "soy sauce", "tofu"],
      instructions: ["Chop veggies", "Stir fry", "Add sauce", "Serve"],
      imageUrl: "",
      cuisineRegion: "Asian",
      proteinChoice: "Tofu",
      dietaryRestriction: "Vegetarian",
      religiousRestriction: "",
      totalLikes: 15,
      totalReviews: 3,
      averageRating: 4.5,
      createdAt: "2024-05-01",
      userLiked: false,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Chicken Curry",
      prepTime: 20,
      cookTime: 30,
      totalTime: 50,
      servings: 4,
      ingredients: ["chicken", "curry powder", "coconut milk", "onion", "rice"],
      instructions: [
        "Cook chicken",
        "Add spices",
        "Simmer with coconut milk",
        "Serve with rice",
      ],
      imageUrl: "",
      cuisineRegion: "Indian",
      proteinChoice: "Chicken",
      dietaryRestriction: "",
      religiousRestriction: "",
      totalLikes: 20,
      totalReviews: 5,
      averageRating: 4.8,
      createdAt: "2024-05-02",
      userLiked: false,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Vegetable Stir Fry",
      prepTime: 10,
      cookTime: 10,
      totalTime: 20,
      servings: 2,
      ingredients: ["broccoli", "carrots", "bell pepper", "soy sauce", "tofu"],
      instructions: ["Chop veggies", "Stir fry", "Add sauce", "Serve"],
      imageUrl: "",
      cuisineRegion: "Asian",
      proteinChoice: "Tofu",
      dietaryRestriction: "Vegetarian",
      religiousRestriction: "",
      totalLikes: 15,
      totalReviews: 3,
      averageRating: 4.2,
      createdAt: "2024-05-03",
      userLiked: true,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Fish Tacos",
      prepTime: 15,
      cookTime: 10,
      totalTime: 25,
      servings: 4,
      ingredients: ["fish", "tortillas", "cabbage", "lime", "sour cream"],
      instructions: [
        "Cook fish",
        "Prepare toppings",
        "Assemble tacos",
        "Serve",
      ],
      imageUrl: "",
      cuisineRegion: "Mexican",
      proteinChoice: "Fish",
      dietaryRestriction: "",
      religiousRestriction: "",
      totalLikes: 8,
      totalReviews: 1,
      averageRating: 4.0,
      createdAt: "2024-05-04",
      userLiked: false,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Beef Stew",
      prepTime: 20,
      cookTime: 120,
      totalTime: 140,
      servings: 6,
      ingredients: ["beef", "potatoes", "carrots", "onion", "beef broth"],
      instructions: ["Brown beef", "Add veggies", "Simmer", "Serve"],
      imageUrl: "",
      cuisineRegion: "American",
      proteinChoice: "Beef",
      dietaryRestriction: "",
      religiousRestriction: "",
      totalLikes: 12,
      totalReviews: 2,
      averageRating: 4.6,
      createdAt: "2024-05-05",
      userLiked: false,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Quinoa Salad",
      prepTime: 10,
      cookTime: 15,
      totalTime: 25,
      servings: 3,
      ingredients: ["quinoa", "tomatoes", "cucumber", "feta", "olive oil"],
      instructions: ["Cook quinoa", "Chop veggies", "Mix", "Serve"],
      imageUrl: "",
      cuisineRegion: "Mediterranean",
      proteinChoice: "",
      dietaryRestriction: "Vegetarian",
      religiousRestriction: "",
      totalLikes: 9,
      totalReviews: 2,
      averageRating: 4.3,
      createdAt: "2024-05-06",
      userLiked: false,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Egg Fried Rice",
      prepTime: 5,
      cookTime: 10,
      totalTime: 15,
      servings: 2,
      ingredients: ["rice", "eggs", "peas", "carrots", "soy sauce"],
      instructions: [
        "Cook rice",
        "Scramble eggs",
        "Stir fry with veggies",
        "Add soy sauce",
      ],
      imageUrl: "",
      cuisineRegion: "Chinese",
      proteinChoice: "Egg",
      dietaryRestriction: "Vegetarian",
      religiousRestriction: "",
      totalLikes: 14,
      totalReviews: 3,
      averageRating: 4.7,
      createdAt: "2024-05-07",
      userLiked: false,
      pageURL: "/settings",
    },
  ],
  userSavedRecipes: [
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Lentil Soup",
      prepTime: 15,
      cookTime: 40,
      totalTime: 55,
      servings: 5,
      ingredients: ["lentils", "carrots", "celery", "onion", "vegetable broth"],
      instructions: [
        "Chop vegetables",
        "Sauté veggies",
        "Add lentils and broth",
        "Simmer until tender",
      ],
      imageUrl: "",
      cuisineRegion: "Middle Eastern",
      proteinChoice: "Lentils",
      dietaryRestriction: "Vegan",
      religiousRestriction: "",
      totalLikes: 18,
      totalReviews: 4,
      averageRating: 4.9,
      createdAt: "2024-05-08",
      userLiked: false,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Shrimp Pad Thai",
      prepTime: 20,
      cookTime: 15,
      totalTime: 35,
      servings: 3,
      ingredients: [
        "rice noodles",
        "shrimp",
        "bean sprouts",
        "peanuts",
        "pad thai sauce",
      ],
      instructions: [
        "Soak noodles",
        "Cook shrimp",
        "Stir fry all ingredients",
        "Top with peanuts",
      ],
      imageUrl: "",
      cuisineRegion: "Thai",
      proteinChoice: "Shrimp",
      dietaryRestriction: "",
      religiousRestriction: "",
      totalLikes: 22,
      totalReviews: 6,
      averageRating: 4.8,
      createdAt: "2024-05-09",
      userLiked: false,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Falafel Wrap",
      prepTime: 25,
      cookTime: 10,
      totalTime: 35,
      servings: 4,
      ingredients: [
        "falafel",
        "pita bread",
        "lettuce",
        "tomato",
        "tahini sauce",
      ],
      instructions: [
        "Prepare falafel",
        "Warm pita",
        "Assemble with veggies and sauce",
        "Wrap and serve",
      ],
      imageUrl: "",
      cuisineRegion: "Mediterranean",
      proteinChoice: "Chickpeas",
      dietaryRestriction: "Vegetarian",
      religiousRestriction: "Halal",
      totalLikes: 13,
      totalReviews: 2,
      averageRating: 4.4,
      createdAt: "2024-05-10",
      userLiked: false,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Turkey Chili",
      prepTime: 15,
      cookTime: 60,
      totalTime: 75,
      servings: 6,
      ingredients: [
        "ground turkey",
        "beans",
        "tomato",
        "onion",
        "chili powder",
      ],
      instructions: [
        "Brown turkey",
        "Add veggies and beans",
        "Simmer with spices",
        "Serve hot",
      ],
      imageUrl: "",
      cuisineRegion: "American",
      proteinChoice: "Turkey",
      dietaryRestriction: "",
      religiousRestriction: "",
      totalLikes: 11,
      totalReviews: 3,
      averageRating: 4.5,
      createdAt: "2024-05-11",
      userLiked: false,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Caprese Salad",
      prepTime: 10,
      cookTime: 0,
      totalTime: 10,
      servings: 2,
      ingredients: [
        "tomato",
        "mozzarella",
        "basil",
        "olive oil",
        "balsamic glaze",
      ],
      instructions: [
        "Slice tomato and mozzarella",
        "Layer with basil",
        "Drizzle with oil and glaze",
        "Serve fresh",
      ],
      imageUrl: "",
      cuisineRegion: "Italian",
      proteinChoice: "",
      dietaryRestriction: "Vegetarian",
      religiousRestriction: "",
      totalLikes: 17,
      totalReviews: 4,
      averageRating: 4.6,
      createdAt: "2024-05-12",
      userLiked: true,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Pancakes",
      prepTime: 10,
      cookTime: 15,
      totalTime: 25,
      servings: 4,
      ingredients: ["flour", "milk", "eggs", "baking powder", "syrup"],
      instructions: [
        "Mix batter",
        "Pour on griddle",
        "Flip when bubbly",
        "Serve with syrup",
      ],
      imageUrl: "",
      cuisineRegion: "American",
      proteinChoice: "Egg",
      dietaryRestriction: "",
      religiousRestriction: "",
      totalLikes: 25,
      totalReviews: 7,
      averageRating: 4.9,
      createdAt: "2024-05-13",
      userLiked: false,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Stuffed Peppers",
      prepTime: 20,
      cookTime: 40,
      totalTime: 60,
      servings: 4,
      ingredients: [
        "bell peppers",
        "rice",
        "ground beef",
        "tomato sauce",
        "cheese",
      ],
      instructions: [
        "Prepare filling",
        "Stuff peppers",
        "Bake with sauce",
        "Top with cheese",
      ],
      imageUrl: "",
      cuisineRegion: "European",
      proteinChoice: "Beef",
      dietaryRestriction: "",
      religiousRestriction: "",
      totalLikes: 10,
      totalReviews: 2,
      averageRating: 4.3,
      createdAt: "2024-05-14",
      userLiked: false,
      pageURL: "/settings",
    },
    {
      username: "mytestuser",
      firstName: "Jane",
      lastName: "Doe",
      name: "Miso Soup",
      prepTime: 5,
      cookTime: 10,
      totalTime: 15,
      servings: 2,
      ingredients: [
        "miso paste",
        "tofu",
        "seaweed",
        "green onion",
        "dashi broth",
      ],
      instructions: [
        "Heat broth",
        "Add miso paste",
        "Stir in tofu and seaweed",
        "Garnish with green onion",
      ],
      imageUrl: "",
      cuisineRegion: "Japanese",
      proteinChoice: "Tofu",
      dietaryRestriction: "Vegan",
      religiousRestriction: "",
      totalLikes: 12,
      totalReviews: 3,
      averageRating: 4.7,
      createdAt: "2024-05-15",
      userLiked: true,
      pageURL: "/settings",
    },
  ],
};

export default hardcodedUser;
